-- ROLE TABLE --
DROP TABLE IF EXISTS ROLES;
DROP sequence IF EXISTS roles_seq;

CREATE sequence roles_seq;
CREATE TABLE ROLES (ID BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('roles_seq'), NAME VARCHAR(255));

-- USER TABLE --
DROP TABLE IF EXISTS USERS;
DROP sequence IF EXISTS users_seq;

CREATE sequence users_seq;
CREATE TABLE USERS (
  ID BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('users_seq'),
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  IS_ACCOUNT_NON_EXPIRED BOOLEAN,
  IS_ACCOUNT_NON_LOCKED BOOLEAN,
  IS_CREDENTIAL_NON_EXPIRED BOOLEAN,
  IS_ENABLED BOOLEAN
  );

-- CATEGORY TABLE --
DROP TABLE IF EXISTS CATEGORY;
DROP sequence IF EXISTS category_seq;

CREATE sequence category_seq;
CREATE TABLE CATEGORY (ID BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('category_seq'), NAME VARCHAR(255));

-- ROLES_TO_USERS TABLE --
DROP TABLE IF EXISTS ROLES_TO_USERS;

CREATE TABLE ROLES_TO_USERS (
  USER_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL
);

-- APPLICATION TABLE --
DROP TABLE IF EXISTS APPLICATION;
DROP sequence IF EXISTS application_seq;

CREATE sequence application_seq;
CREATE TABLE APPLICATION (
  ID BIGINT NOT NULL PRIMARY KEY DEFAULT NEXTVAL('application_seq'),
  CATEGORY_ID BIGINT,
  APPLICATION_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  PACKAGE_NAME VARCHAR(255),
  PICTURE_128  VARCHAR(255),
  PICTURE_512 VARCHAR(255),
  DOWNLOADS_QUANTITY BIGINT,
  UPLOAD_DATE timestamp,
  IMAGE_128 BYTEA,
  IMAGE_512 BYTEA
);