-- ROLE TABLE --
INSERT INTO ROLES (NAME) VALUES ('DEVELOPER');
INSERT INTO ROLES (NAME) VALUES ('USER');

-- USER TABLE --
INSERT INTO USERS (
  USERNAME,
  PASSWORD,
  IS_ACCOUNT_NON_EXPIRED,
  IS_ACCOUNT_NON_LOCKED,
  IS_CREDENTIAL_NON_EXPIRED,
  IS_ENABLED
) VALUES ('user', 'user', true, true, true, true);
INSERT INTO USERS (
  USERNAME,
  PASSWORD,
  IS_ACCOUNT_NON_EXPIRED,
  IS_ACCOUNT_NON_LOCKED,
  IS_CREDENTIAL_NON_EXPIRED,
  IS_ENABLED
) VALUES ('dev', 'dev', true, true, true, true);

-- ROLES_TO_USERS TABLE --
INSERT INTO ROLES_TO_USERS (USER_ID, ROLE_ID) VALUES (
(SELECT ID FROM USERS WHERE USERNAME = 'user'),
(SELECT ID FROM ROLES WHERE NAME = 'USER'));
INSERT INTO ROLES_TO_USERS (USER_ID, ROLE_ID) VALUES (
(SELECT ID FROM USERS WHERE USERNAME = 'dev'),
(SELECT ID FROM ROLES WHERE NAME = 'DEVELOPER'));

-- CATEGORY TABLE --
INSERT INTO CATEGORY (NAME) VALUES ('GAMES');
INSERT INTO CATEGORY (NAME) VALUES ('MULTIMEDIA');
INSERT INTO CATEGORY (NAME) VALUES ('PRODUCTIVITY');
INSERT INTO CATEGORY (NAME) VALUES ('TOOLS');
INSERT INTO CATEGORY (NAME) VALUES ('HEALTH');
INSERT INTO CATEGORY (NAME) VALUES ('LIFESTYLE');
INSERT INTO CATEGORY (NAME) VALUES ('VEHICLES');
INSERT INTO CATEGORY (NAME) VALUES ('EDUCATION');
INSERT INTO CATEGORY (NAME) VALUES ('TRAVELING');